### PR TITLE
fix: apply validateResponseOnClient recursively

### PR DESCRIPTION
**Pull request by uooq**

### CODE REVIEW

**Comment by michaelangeloio** [comment]
hi @uooq , looks like there are some test failures, mind checking them out?

**Comment by michaelangeloio** [comment]
Ah nevermind, I see it's an issue with PNPM version

**Comment by michaelangeloio** [comment]
@uooq can you sync with main branch? Should unblock your PR from passing the tests!

**Comment by uooq** [comment]
> @uooq can you sync with main branch? Should unblock your PR from passing the tests!

Sure, done.  (Please note that everything was synced when I submitted the original PR, it was your commit yesterday that made it stale. The only check that I saw failing was the Vercel "authorization required to deploy")

**Comment by michaelangeloio** [comment]
> > @uooq can you sync with main branch? Should unblock your PR from passing the tests!
> 
> Sure, done. (Please note that everything was synced when I submitted the original PR, it was your commit yesterday that made it stale. The only check that I saw failing was the Vercel "authorization required to deploy")

Yes, that commit was to bump the pnpm version which allows our CI to run all tests. Running the tests for you now!

**Comment by uooq** [comment]
Am I meant to sign up for a Vercel account to get that check to run?

**Comment by uooq** [comment]
I tried creating a vercel account and then authorized the deployment, but nothing happened.  There's no mention of what to do in the contributing readme or I'd do it.

**Review by michaelangeloio — APPROVED** [review]

**Pull request merged**
