### PR TITLE
chore: upgrade to nx 16

### PR DESCRIPTION
**Pull request by oliverbutler**

### CODE REVIEW

**Review by Gabrola — APPROVED** [review]
Nice!

**Review by Gabrola — APPROVED** [review]
🚢 it

**Comment by Gabrola** [comment]
@all-contributors
please add @oliverbutler for code, ideas, docs, infra and maintenance.
please add @michaelangrivera for code, ideas and maintenance.
please add @Gabrola for maintenance.

**Comment by oliverbutler** [comment]
glad us three are finally getting some credit for our contributions /s 😅

**Pull request merged**
