### PR TITLE
omit queryKey from react-query options

### PR DESCRIPTION
**Pull request by AdhamMoussa**
#442

### CODE REVIEW

**Comment by Gabrola** [comment]
This will not fix anything as this change only changes the types for the internal API. The external facing types are here https://github.com/ts-rest/ts-rest/blob/main/libs/ts-rest/react-query/src/lib/types.ts

But I'm curious as to why you are getting this issue in the first place. `queryKey` is optional in the query options and I've never come across this issue before. @iceStorm can you make a quick reproducible repo or codesandbox?

**Comment by iceStorm** [comment]
@Gabrola please kindly take a look at the following reproduction:

https://github.com/iceStorm/ts-rest-query-key-issue?tab=readme-ov-file#ts-restreact-query-querykey-issue

**Comment by Gabrola** [comment]
@iceStorm the problem in your repo is that you have v5 of @tanstack/react-query installed which is incompatible with ts-rest. Simply installing v4 and adding it into your package.json will fix the problem. It seems that v5 was added to our valid peer dependencies in a recent PR, hence why it was installed automatically due to the fact that pnpm now installs peerDependencies by default instead of warning you. I will fix this now.

**Comment by AdhamMoussa** [comment]
@Gabrola why do we need to stick with v4 instead of fixing the actual issue?
tbh this whole package for react-query is useless anyway. I don't see any value from it since the only thing it does is passing the arguments to the fetch function. it has poor TS types and a lot of issues. I ended up removing this package and just using react-query directly with ts-rest client. much better experience

**Comment by Gabrola** [comment]
@AdhamMoussa because v5 is a breaking change. We cannot support both v4 and v5 at the same time, and since all of the ts-rest package versions are synchronized we'd have to release a major version release for all @ts-rest/* packages. We'd like to keep it the same way as it removes any complexity of compatibility between the different packages. Tackstack query v4 is still the most downloaded version until now, so there's no rush to upgrade. We also have other features and changes planned for ts-rest v4, so we'd rather have to release only one breaking major version release.

**Comment by AdhamMoussa** [comment]
@Gabrola makes sense. Thanks

**Pull request closed without merging**
