### PR TITLE
add docs for @fastify/swagger and @fastify/swagger-ui

### PR DESCRIPTION
**Pull request by dohaicuong**

### CODE REVIEW

**Comment by oliverbutler** [comment]
This is great thanks @dohaicuong ! I left a couple of comments on the Vercel deployment https://ts-rest-git-fork-dohaicuong-main-ts-rest.vercel.app/docs/fastify/openapi

other than that, this is great.

**Review by oliverbutler — CHANGES_REQUESTED** [review]
This is great thanks @dohaicuong ! A couple comments from me then it's perfect IMO.

Missing backtick on @fastify/swagger-ui first paragraph
Do you think it's worth explaining that you can just serve the openAPI doc as a JSON file, and this guide is how to server a Swagger UI if you fancy it
In Generating a OpenAPI Document can we link to the original @ts-rest/open-api docs so they're connected
Then lets get this merged thanks.

**Comment by dohaicuong** [comment]
> This is great thanks @dohaicuong ! A couple comments from me then it's perfect IMO.
> 
> * Missing backtick on @fastify/swagger-ui first paragraph
> * Do you think it's worth explaining that you can just serve the openAPI doc as a JSON file, and this guide is how to server a Swagger UI if you fancy it
> * In Generating a OpenAPI Document can we link to the original @ts-rest/open-api docs so they're connected
> 
> Then lets get this merged thanks.

I have addressed your comment :+1: 

Let me know if you want to make changes with the writing through...

**Review by oliverbutler — APPROVED** [review]
Thanks for making the changes - this looks great thanks!

@all-contributors please add @dohaicuong for docs

**Comment by oliverbutler** [comment]
@all-contributors please add @dohaicuong for docs

**Pull request merged**
