### PR TITLE
chore: fix ESM support

### LINKED ISSUE #66: initQueryClient seems invalid in @ts-rest/react-query
Hey @oliverbutler 
First thanks for this amazing tool!
I ran an error while using `@ts-rest/react-query` : `No QueryClient set, use QueryClientProvider to set one` (nx, cra/nest)

This problem happens only with the compiled package, I have no error when I copy the client from your monorepo and then create my own lib.

### PR DESCRIPTION
**Pull request by michaelangrivera**
## Context

Hope to officially close #66 without workarounds. To be clear, I _do not_ want to merge these changes just yet, but I want to get at least the conversation going, and a PR started so that we can implement @ecyrbe 's suggestions or our own fix. 

## Background

On my NextJS webpack build, and several others, we observe the following error: 
```
Server Error
Error: No QueryClient set, use QueryClientProvider to set one

This error happened while generating the page. Any console logs will be displayed in the terminal window.
```

Implementing this workaround no longer works for me (for some reason): 

```
    if (options.isServer) {
      config.externals = ["@tanstack/react-query", ...config.externals];
    }
    const reactQuery = path.resolve(require.resolve("@tanstack/react-query"));
    console.log(reactQuery, 'converted ts-rest imports for react-query')
    config.resolve.alias["@tanstack/react-query"] = reactQuery;
    return config;
  },
```

According to #66  and @ecyrbe, the likely culprit is that exports are not being correctly interpreted by webpack. See: https://github.com/ecyrbe/zodios/issues/191#issuecomment-1288101919. 

I released a temporary test version of `@ts-rest/react-query` here: https://www.npmjs.com/package/michaelangrivera-ts-rest-react-query, and I still see the same issue while implementing that suggestion. 

Interestingly, though, the following works:
```
`const client = require('michaelangrivera-ts-rest-react-query')`
```
I guess this is to be expected, though, since ESM is failing and not common modules. 

This is what the build looks like after `nx build` for that library:
```
{
  "name": "michaelangrivera-ts-rest-react-query",
  "version": "3.6.6",
  "description": "react-query client integration for @ts-rest",
  "license": "MIT",
  "main": "./index.cjs",
  "module": "./index.js",
  "typings": "index.d.ts",
  "exports": {
    ".": {
      "types": "./index.d.ts",
      "import": "./index.js",
      "require": "./index.cjs"
    },
    "./package.json": "./package.json"
  },
....
  "peerDependencies": {
    "react": "16.x.x || 17.x.x || 18.x.x",
    "zod": "3.x.x",
    "@tanstack/react-query": "4.x.x",
    "@ts-rest/core": "3.6.0"
  },
  "type": "module",
  "types": "./index.d.ts",
  "dependencies": {}
}
```

I tried the following changes (I published them, re-installed, and cleared .next cache):
-  `"generateExportsField": true,` no luck
- only using `esm` under the `format` configuration, no luck

I'm wondering if changing `type:` to `module` in `package.json` would work any magic. 

Let me know if you have any suggestions, and I can implement, test them, and then update this PR @oliverbutler @ecyrbe.

I could also be totally off, and this is actual a `client` instance issue with React Query and the way it's be initialized. 

This whole effort may be futile as Next is moving away from webpack, but nonetheless, it may still be good to support webpack for legacy apps and people using webpack without Next.

### CODE REVIEW

**Comment by oliverbutler** [comment]
I've got a lot more time to build ts-rest these days, I'll look over this! I *attempted* the fix the other day, need to try replicate it. 

Quick note, make sure you use pnpm!

**Comment by ecyrbe** [comment]
Hello, 
Once thing to diagnose the issue for sure on your side is using webpack bundle analyzer:
```js
 const withBundleAnalyzer = require("@next/bundle-analyzer")({
   enabled: process.env.ANALYZE === "true",
 });
 
 /** @type {import('next').NextConfig} */
 const nextConfig = {
   reactStrictMode: true,
   swcMinify: true,
 };
 
 module.exports = withBundleAnalyzer(nextConfig);
```
Check carrefully if  `@tansctack/react-query` is bundled twice (if you see both .mjs and js files)

I know you may already checked this, but just in case :  
- check also if your lock file contains two different versions of `@tanstack/query`
- check that you have react-query provider setup in your react tree (usually you put it on _app )

One thing that might help is provide a reproductible setup

**Comment by oliverbutler** [comment]
Shall we spin up a Next.js app in the repo (not NX? or maybe both?) which can import the *built* @ts-rest/react-query package so we can try replicate locally to help fix this ASAP?

Happy to help out.

**Comment by oliverbutler** [comment]
Hey @michaelangrivera, I believe Next is working perfectly currently...? https://next-example.ts-rest.com 

Source code is in the ts-rest team repo called next-example (using @ts-rest 3.10.2)

**Comment by oliverbutler** [comment]
Closing right now, let's loop back around to this is anyone experiences the issue and can replicate it! 🙏

**Comment by michaelangrivera** [comment]
Hi! @oliverbutler I believe it was a user error 😓 My apologies. 
I upgraded to Next 13 and did a little refactoring in my app, and I noticed I had the query client _within_ the `_app` root component like so:

```
function app({}) {
  const queryClient = new QueryClient()

  return ( <QueryClientProvider client={queryClient}>)
}
```
I'm thinking this might've caused some weird behavior?
Either way, it's working now! 

@oliverbutler Want to talk to you about some features I'd like to work on if I can. Can I hit you up on twitter?

**Comment by oliverbutler** [comment]
Ah! Possibly either that _or_ because @Gabrola and I made some improvements on the package.json! regardless, not my area of expertise so I'm super happy it seems to be resolved 🤞 

Twitter, or a Github discussion, or a Discord channel (I'm tempted to make one for @ts-rest not 100% sure yet) 

Would love to help out, there's a bunch of next steps I'd love to take with the lib

**Comment by michaelangrivera** [comment]
@oliverbutler Sweet! I'll hyu. Discord channel or slack would be awesome.

**Comment by oliverbutler** [comment]
@michaelangrivera https://discord.com/invite/2Megk85k5a, guess we'll see how this goes. Bit easier for back forth DMs.

**Comment by michaelangrivera** [comment]
@oliverbutler hell yeah, I'll join right now!

**Pull request closed without merging**
