### PR TITLE
fix: fastify deprecated routerPath property

### PR DESCRIPTION
**Pull request by btravers**
Fix https://github.com/ts-rest/ts-rest/issues/392

### CODE REVIEW

**Comment by Geebrox** [comment]
Any progress on this?

**Comment by btravers** [comment]
I am waiting for a review. 

In the meantime, I patched the library on my project using `pnpm patch` with the same fix.

**Review by oliverbutler — APPROVED** [review]
Hey @btravers ! 

Thanks for the PR, sorry it took so long to get around to checking this sound.

Thanks for the issue and for the fix, LGTM.

**Comment by btravers** [comment]
Ok, I have just rebased my main branch.

**Comment by michaelangeloio** [comment]
@btravers mind syncing with main branch and checking out if the failed tests are related?

**Comment by btravers** [comment]
@michaelangeloio I've just sync my branch

**Comment by btravers** [comment]
I add a new commit, `routerPath` does not exist anymore.

**Pull request merged**
